# SPDX-License-Identifier: Apache-2.0
# 加速度センサに関する設定
CONFIG_SENSOR=y
CONFIG_MPU6050=y
CONFIG_I2C=y

# メインスレッドのスタックサイズ
CONFIG_MAIN_STACK_SIZE=2048

# 64ビット整数を含む整数の書式変換を有効にする
CONFIG_CBPRINTF_FULL_INTEGRAL=y

# ロギングに関する設定
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=1
CONFIG_LOG_BUFFER_SIZE=4096
